### ISSUE TITLE
Bandit compatible?

### ISSUE THREAD

**Issue by niccolox** [tanguilp/plug_http_cache#3]
hi
is this ecosystem compatible with Bandit?

**Comment by tanguilp** [comment]
Hello,

Should be, since Bandit supports the Plug interface. Not tested so far though.

**Comment by niccolox** [comment]
it worked for me in basic testing

closing for now

**Comment by niccolox** [comment]
I've been running my hobby project in production using Edeliver/Distillery and also now Ansible on OTP26 and its working fine with Bandit
